"""Tour page content for Cozumel Cruise Excursion."""
from cozumel_config import (
    ATV_IMG, ATV_ALT, BEACH_DAY_IMG, BEACH_DAY_ALT, BEST_OF_IMG, BEST_OF_ALT,
    CATAMARAN_IMG, CATAMARAN_ALT, CHANKANAAB_IMG, CHANKANAAB_ALT,
    EL_CIELO_IMG, EL_CIELO_ALT,
    CRYSTAL_IMG, CRYSTAL_ALT, JEEP_IMG, JEEP_ALT, MR_SANCHOS_IMG, MR_SANCHOS_ALT,
    PRIVATE_ISLAND_IMG, PRIVATE_ISLAND_ALT, RUINS_IMG, RUINS_ALT,
    SCUBA_IMG, SCUBA_ALT, SNORKEL_IMG, SNORKEL_ALT,
    TEQUILA_IMG, TEQUILA_ALT,
)
from cozumel_helpers import content_tour_page


def all_tour_content() -> dict[str, str]:
    return {
        "best-of-cozumel.html": content_tour_page(
            "The Best of Cozumel tour distills the island into one cruise-friendly day — serene west-coast beaches, vibrant San Miguel markets, historic sites and a tequila tasting at a local hacienda before exploring downtown. Ideal for first-time visitors who want culture, scenery and a taste of Mexico without committing to a single activity.",
            [
                "5-hour format fits most 6–10 hour Cozumel port calls.",
                "Combines beach time, Mayan heritage and downtown exploration.",
                "Port pickup from Punta Langosta, International Pier and Puerta Maya.",
                "Tequila tasting introduces regional agave culture in a relaxed setting.",
            ],
            [
                (BEACH_DAY_IMG, BEACH_DAY_ALT, "West-Coast Beaches", "Calm Caribbean water and sandy stretches along Cozumel's leeward shore."),
                (RUINS_IMG, RUINS_ALT, "Mayan Heritage", "Historic sites and cultural context across the island."),
                (TEQUILA_IMG, TEQUILA_ALT, "Tequila Tasting", "Sample authentic Mexican spirits at a Cozumel hacienda."),
            ],
            dict(best_for="First-time visitors and culture seekers", activity_level="Moderate", popular="Island highlights, tequila, downtown"),
            BEST_OF_IMG, BEST_OF_ALT,
            badge="Best for First-Time Visitors",
            extra_links=[("best-of-cozumel.html", "Best of Cozumel"), ("cozumel-tequila-tasting-tour.html", "Tequila Tour")],
        ),
        "cozumel-beach-day.html": content_tour_page(
            "A dedicated Cozumel beach day suits cruise passengers who want turquoise water, loungers and a slower pace without a packed activity list. West-coast clubs and day passes differ in atmosphere and inclusions — check what your operator actually provides for your date rather than assuming a fixed package.",
            [
                "Often fits a half-day or longer call with transfers from the main piers.",
                "Ask what food, drinks and amenities are included before you pay.",
                "Easy activity level for families, couples and anyone wanting low logistics.",
                "Leave a clear return buffer; do not cut taxi time fine on multi-ship days.",
            ],
            [
                (CRYSTAL_IMG, CRYSTAL_ALT, "West-coast water", "Protected leeward bays are the usual cruise-friendly choice."),
                (BEACH_DAY_IMG, BEACH_DAY_ALT, "Club amenities", "Loungers and shade vary by property — compare before you choose."),
                (SNORKEL_IMG, SNORKEL_ALT, "Optional snorkel", "Some beach locations offer shore or nearby reef access."),
            ],
            dict(best_for="Relaxed port days and sun seekers", activity_level="Easy", family="Excellent for all ages", popular="Beach clubs, day passes"),
            BEACH_DAY_IMG, BEACH_DAY_ALT,
            badge="Best for an easy beach day",
            extra_links=[("mr-sanchos-beach-club.html", "Mr Sanchos"), ("cozumel-reef-vs-beach.html", "Reef vs beach")],
        ),
        "cozumel-snorkeling-tour.html": content_tour_page(
            "Cozumel sits on the Mesoamerican Reef — the Caribbean’s great underwater draw for cruise passengers. Boat snorkel days often visit sites such as Palancar, Columbia Reef and the El Cielo sandbar. Sightings and visibility change with conditions; treat wildlife as a possibility, not a promise.",
            [
                "Typical boat formats leave time for multiple water stops within a cruise call — confirm duration with the operator.",
                "Morning departures are often preferred when seas are calmer on the leeward coast.",
                "Basic swimming comfort helps; ask about flotation support if you are a nervous snorkeller.",
                "Reef-safe sunscreen or a rash guard is kinder to the marine park environment.",
            ],
            [
                (SNORKEL_IMG, SNORKEL_ALT, "Palancar Reef", "Dramatic reef structure along Cozumel's south coast when conditions allow."),
                (EL_CIELO_IMG, EL_CIELO_ALT, "El Cielo sandbar", "Shallow turquoise water — marine life varies day to day."),
                (SNORKEL_IMG, SNORKEL_ALT, "Guided water time", "Operators set the pace; follow briefings and marine-park guidance."),
            ],
            dict(best_for="Swimmers and reef enthusiasts", activity_level="Moderate — boat and swim", popular="El Cielo, Palancar, Columbia Reef"),
            SNORKEL_IMG, SNORKEL_ALT,
            badge="Best for reef time",
            extra_links=[("cozumel-catamaran-sail-and-snorkel.html", "Catamaran snorkel"), ("cozumel-reef-vs-beach.html", "Reef vs beach")],
        ),
        "chankanaab-park-tour.html": content_tour_page(
            "Chankanaab National Marine Park is a popular cruise-day stop south of the piers — lagoon and beach facilities, a house reef snorkel zone, and optional animal programs depending on what is offered on the day. Journey time depends on which terminal you use and traffic.",
            [
                "Often fits within a half-day or longer call once transfers are included — confirm duration with the operator.",
                "House reef snorkel is commonly available; gear hire and add-ons vary by package.",
                "A short taxi or organised transfer from the main cruise terminals for many ships.",
                "Lockers, showers and food outlets are typically available inside the park.",
            ],
            [
                (CHANKANAAB_IMG, CHANKANAAB_ALT, "Lagoon &amp; Beach", "Calm swimming areas and shaded palapas along the shore."),
                (SNORKEL_IMG, SNORKEL_ALT, "House Reef", "Snorkel directly from Chankanaab's protected reef zone."),
                (CHANKANAAB_IMG, CHANKANAAB_ALT, "Marine Encounters", "Optional dolphin, manatee and sea lion programs."),
            ],
            dict(best_for="Families wanting one-stop island fun", activity_level="Easy to moderate", family="Excellent — check age limits for animal programs", popular="Chankanaab snorkel, dolphin swim, park pass"),
            CHANKANAAB_IMG, CHANKANAAB_ALT,
            badge="Best for Families",
            extra_links=[("chankanaab-park-guide.html", "Chankanaab Guide"), ("cozumel-scuba-diving-tour.html", "Scuba at Chankanaab")],
        ),
        "mr-sanchos-beach-club.html": content_tour_page(
            "Mr Sanchos on Cozumel’s west coast is a well-known beach-club style day for cruise passengers who want loungers, a pool and a social atmosphere away from the pier. Treat package details as operator-specific — confirm food, drinks and transfer arrangements for your sailing rather than relying on generic descriptions.",
            [
                "Popular on busy ship days — reserve early if your dates are crowded.",
                "Typical visits leave time for swimming and lounging within a cruise call.",
                "Transfers are usually by taxi or organised vehicle from the cruise terminals.",
                "Compare with Chankanaab if you also want a structured park and house reef.",
            ],
            [
                (BEACH_DAY_IMG, BEACH_DAY_ALT, "Palm-tree beach", "West-coast lounging when you want a slower port day."),
                (CRYSTAL_IMG, CRYSTAL_ALT, "Calm swimming", "Leeward water is the usual cruise-friendly setting."),
                (SNORKEL_IMG, SNORKEL_ALT, "Optional water time", "Ask what snorkel access looks like on your chosen package."),
            ],
            dict(best_for="Couples and groups wanting hassle-free beach time", activity_level="Easy", family="Popular with families — check current rules", popular="Mr Sanchos day pass, west-coast beach clubs"),
            MR_SANCHOS_IMG, MR_SANCHOS_ALT,
            badge="Best for a classic beach club day",
            extra_links=[("mr-sanchos-cozumel-guide.html", "Mr Sanchos guide"), ("cozumel-beach-day.html", "Beach day options")],
        ),
        "cozumel-jeep-tour.html": content_tour_page(
            "Cozumel jeep tours blaze through jungle trails to El Cedral — the island's oldest Mayan settlement — then splash into Jade Caverns cenote and finish with a guided snorkel at Dzul-Ha Reef. Open-top jeeps, small groups and mixed terrain make this one of Cozumel's top adventure shore excursions.",
            [
                "5-hour adventure with snorkel gear and beverages included.",
                "Moderate activity — bumpy jungle roads and water entry.",
                "Driver's licence required for guests who want to drive.",
                "Not ideal to combine with a separate long snorkel catamaran same day.",
            ],
            [
                (JEEP_IMG, JEEP_ALT, "Jungle Trails", "Off-road driving through Cozumel's interior landscapes."),
                (RUINS_IMG, RUINS_ALT, "El Cedral Ruins", "Oldest Mayan site on the island with cultural commentary."),
                (SNORKEL_IMG, SNORKEL_ALT, "Dzul-Ha Reef Snorkel", "Guided reef snorkel after cenote swim at Jade Caverns."),
            ],
            dict(best_for="Adventure seekers and active couples", activity_level="Moderate — driving and swimming", popular="Jungle jeep, cenote, reef snorkel combo"),
            JEEP_IMG, JEEP_ALT,
            badge="Best Adventure Tour",
            extra_links=[("cozumel-atv-adventure.html", "ATV Adventure"), ("cozumel-mayan-ruins-tour.html", "Mayan Ruins")],
        ),
        "cozumel-mayan-ruins-tour.html": content_tour_page(
            "San Gervasio is Cozumel’s main Mayan archaeological site — a sacred complex associated with Ixchel. It is a genuine cultural stop, but it is not equivalent to major mainland ruins. Shore excursions explore temple areas and island history, sometimes paired with beach time on the return leg.",
            [
                "Island logistics only — no ferry required.",
                "Expect walking on uneven surfaces; sturdy shoes help.",
                "Transfer time across the island matters on shorter calls.",
                "For flagship mainland archaeology, read island vs mainland first.",
            ],
            [
                (RUINS_IMG, RUINS_ALT, "San Gervasio", "Mayan structures in Cozumel's interior."),
                (RUINS_IMG, RUINS_ALT, "Cultural context", "Guides explain island history without overselling scale."),
                (BEACH_DAY_IMG, BEACH_DAY_ALT, "Optional beach add-on", "Some routes add west-coast time after the ruins."),
            ],
            dict(best_for="History-minded passengers staying on-island", activity_level="Low to moderate — walking", popular="San Gervasio ruins, Mayan culture tours"),
            RUINS_IMG, RUINS_ALT,
            badge="Best on-island ruins day",
            extra_links=[("cozumel-island-vs-mainland.html", "Island vs mainland"), ("best-of-cozumel.html", "Best of Cozumel")],
        ),
        "cozumel-catamaran-sail-and-snorkel.html": content_tour_page(
            "Catamaran sail-and-snorkel days are a common Cozumel water format — time under sail or motor, reef stops when conditions allow, and a calmer pace than a packed multi-stop land tour. Exact routes, lunch and drink inclusions depend on the operator and sea state.",
            [
                "Often planned as a multi-hour water day within a typical cruise call — confirm timing before you book.",
                "Operators may adjust sites in wind or swell; nothing on the reef is guaranteed.",
                "Basic swimming comfort helps; ask about flotation support if needed.",
                "Leave a clear return buffer; do not cut transfers fine on busy ship days.",
            ],
            [
                (CATAMARAN_IMG, CATAMARAN_ALT, "Caribbean Sailing", "Spacious decks and shade while crossing Cozumel's leeward coast."),
                (SNORKEL_IMG, SNORKEL_ALT, "Reef Snorkel Stops", "Colombia Reef and marine park sites with guide supervision."),
                (EL_CIELO_IMG, EL_CIELO_ALT, "El Cielo Sandbar", "Iconic shallow sandbar with starfish and turquoise water."),
            ],
            dict(best_for="Couples and snorkel lovers", activity_level="Moderate — boat and swim", popular="Catamaran El Cielo, Colombia Reef sail"),
            CATAMARAN_IMG, CATAMARAN_ALT,
            badge="Best Snorkeling Tour",
            extra_links=[("cozumel-snorkeling-tour.html", "Snorkeling Tours"), ("cozumel-private-island-tour.html", "Private Island")],
        ),
        "cozumel-atv-adventure.html": content_tour_page(
            "ATV days on Cozumel are for passengers who want an active land outing rather than a beach lounge. Routes, vehicle types and age rules vary by operator — treat duration and inclusions as package-specific, and expect heat, dust and uneven surfaces.",
            [
                "Riding time is usually measured in hours rather than a full day, plus briefing and transfers — confirm with the operator.",
                "A valid driving licence is commonly required; minimum ages vary.",
                "Moderate to high effort — closed-toe shoes and clothes you do not mind getting dusty help.",
                "Not a substitute for reef time if underwater scenery is your priority.",
            ],
            [
                (ATV_IMG, ATV_ALT, "Jungle Trails", "Guided ATV routes through Cozumel's interior terrain."),
                (ATV_IMG, ATV_ALT, "Coastal stretches", "Some operators include open stretches between forest sections — confirm the route."),
                (ATV_IMG, ATV_ALT, "Safety Briefing", "Helmets, instruction and small-group guide ratios."),
            ],
            dict(best_for="Thrill seekers and active adults", activity_level="Moderate to high", family="Older teens only — check age policy", popular="ATV jungle trails, adventure parks"),
            ATV_IMG, ATV_ALT,
            badge="Best Adventure Tour",
            extra_links=[("cozumel-jeep-tour.html", "Jeep Tour")],
        ),
        "cozumel-tequila-tasting-tour.html": content_tour_page(
            "Tequila tasting excursions on Cozumel pair agave education with island time — sample styles such as blanco, reposado and añejo when the operator offers them, often alongside sightseeing or light adventure. Pour counts, food and any zip-line add-ons are package-specific.",
            [
                "Usually a half-day style outing; combos with snorkel or adventure extend the clock.",
                "Eat beforehand and hydrate — tasting pours add up in tropical heat.",
                "Easy to moderate unless a zip-line or similar add-on is included.",
                "Check minimum ages and what is actually included before you pay.",
            ],
            [
                (TEQUILA_IMG, TEQUILA_ALT, "Agave Education", "Learn tequila categories and traditional production."),
                (TEQUILA_IMG, TEQUILA_ALT, "Guided Tastings", "Sample premium Mexican tequilas with expert commentary."),
                (BEST_OF_IMG, BEST_OF_ALT, "Hacienda Setting", "Tastings at island haciendas and adventure parks."),
            ],
            dict(best_for="Adults and culture enthusiasts", activity_level="Easy to moderate", popular="Tequila tasting, zip-and-sip, culinary tours"),
            TEQUILA_IMG, TEQUILA_ALT,
            badge="Best for First-Time Visitors",
            extra_links=[("best-of-cozumel.html", "Best of Cozumel")],
        ),
        "cozumel-private-island-tour.html": content_tour_page(
            "Private or small-group boat days aim for quieter sand and water time away from the busiest pier plazas. Exact beaches, sandbars and inclusions vary widely — confirm the meeting point, return plan and what food or snorkel gear is included for your date.",
            [
                "Usually a multi-hour boat day within a cruise call — confirm the schedule.",
                "Higher per-person cost often buys smaller groups and more flexible pacing.",
                "Sea conditions can change the stop list; build buffer for the return.",
                "Useful for celebrations and groups who want privacy over a fixed itinerary.",
            ],
            [
                (PRIVATE_ISLAND_IMG, PRIVATE_ISLAND_ALT, "Secluded Beaches", "White sand and calm water away from cruise crowds."),
                (CATAMARAN_IMG, CATAMARAN_ALT, "Private Boat Access", "Reach sandbars and coves only accessible by water."),
                (SNORKEL_IMG, SNORKEL_ALT, "Snorkel On Demand", "Stop at reef patches when conditions allow."),
            ],
            dict(best_for="Groups wanting privacy and custom timing", activity_level="Easy to moderate", popular="Private catamaran, El Cielo charter, island escape"),
            PRIVATE_ISLAND_IMG, PRIVATE_ISLAND_ALT,
            badge="Best Private Option",
            extra_links=[("cozumel-catamaran-sail-and-snorkel.html", "Catamaran Tours")],
        ),
        "cozumel-scuba-diving-tour.html": content_tour_page(
            "Cozumel’s reefs support introductory and certified diving for cruise passengers when operators and medical screening allow it. Discover scuba and short reef dives are commonly offered around park or marina bases — exact sites and tank counts depend on certification, conditions and the operator.",
            [
                "Plan on a multi-hour outing including briefing and kit — confirm the timetable.",
                "A medical questionnaire is standard; disclose conditions honestly.",
                "Moderate effort; comfort in water is essential.",
                "Do not stack a long mainland day with a first dive unless your call clearly supports both.",
            ],
            [
                (SCUBA_IMG, SCUBA_ALT, "Reef Diving", "Coral walls and tropical fish along Cozumel's marine park."),
                (CHANKANAAB_IMG, CHANKANAAB_ALT, "Chankanaab Dive Site", "Controlled entry with park facilities and post-dive beach time."),
                (SCUBA_IMG, SCUBA_ALT, "Discover Scuba", "Introductory dives for guests without certification."),
            ],
            dict(best_for="Certified divers and adventurous beginners", activity_level="Moderate — diving", popular="Discover scuba, one-tank Chankanaab dive"),
            SCUBA_IMG, SCUBA_ALT,
            badge="Best Snorkeling Tour",
            extra_links=[("chankanaab-park-tour.html", "Chankanaab Park"), ("cozumel-snorkeling-tour.html", "Snorkeling")],
        ),
    }
